Repository Cemag-pcp/sistema_epi_v2, pull requests merged in 2025-05, with the labels that each got.

#5 :wrench: chore: Configurando base, dev e prod
  sistema_epi_v2/settings/base.py
  sistema_epi_v2/settings/dev.py
  sistema_epi_v2/settings/prod.py
Labels: configuracao

#10 criação de perfis de usuario, decorators de master, autenticação
  core/templates/base.html
  core/templates/home.html
  core/views.py
  sistema_epi_v2/urls.py
  usuario/admin.py
  usuario/decorators.py
  usuario/migrations/0004_funcionario_remove_usuario_ativo_and_more.py
  usuario/migrations/0005_alter_usuario_funcionario.py
  usuario/migrations/0006_alter_usuario_funcionario.py
  usuario/migrations/0007_alter_usuario_funcionario.py
  usuario/models.py
  usuario/templates/usuario/login.html
  usuario/urls.py
  usuario/views.py
Labels: funcionalidade

#11 :sparkles: feat: Layout CRUD de equipamentos
  core/templates/base.html
  equipamento/static/js/crud-equipamentos.js
  equipamento/templates/equipamento.html
  equipamento/templates/modal/modal_equipamento.html
  static/css/crud.css
  static/css/status.css
Labels: funcionalidade

#13 Funcionalidade/autenticacao controle de acesso
  usuario/static/js/scripts_login.js
  usuario/templates/usuario/login.html
  usuario/views.py
Labels: melhoria

#15 :lipstick: style: Layout de Solicitação
  core/templates/base.html
  sistema_epi_v2/urls.py
  solicitacao/templates/solicitacao.html
  solicitacao/urls.py
  solicitacao/views.py
Labels: funcionalidade

#19 :sparkles: feat: Iniciando os Padroes
  core/templates/base.html
  padrao/migrations/0004_rename_cargo_padrao_nome.py
  padrao/models.py
  padrao/templates/padroes.html
  padrao/urls.py
  padrao/views.py
  sistema_epi_v2/settings/base.py
  sistema_epi_v2/urls.py
  solicitacao/static/js/clone.js
  solicitacao/templates/solicitacao.html
  solicitacao/urls.py
Labels: funcionalidade

#20 Funcionalidade/funcionario
  usuario/static/js/crud_funcionario.js
  usuario/static/js/datatable_funcionario.js
  usuario/templates/usuario/funcionario.html
  usuario/templates/usuario/modal/modal_funcionario.html
  usuario/urls.py
  usuario/views.py
Labels: funcionalidade

#23 Funcionalidade/funcionario
  usuario/admin.py
  usuario/migrations/0021_remove_funcionario_responsavel_setor_responsavel.py
  usuario/migrations/0022_alter_setor_responsavel.py
  usuario/models.py
  usuario/static/js/crud_funcionario.js
  usuario/static/js/datatable_funcionario.js
  usuario/templates/usuario/funcionario.html
  usuario/templates/usuario/modal/modal_funcionario.html
  usuario/urls.py
  usuario/views.py
Labels: melhoria

#24 Funcionalidade/padroes
  core/templates/base.html
  equipamento/static/js/addRow.js
  equipamento/static/js/crud-equipamentos.js
  equipamento/static/js/datatable-equipamentos.js
  equipamento/templates/equipamento.html
  equipamento/views.py
  padrao/admin.py
  padrao/migrations/0001_initial.py
  padrao/migrations/0002_delete_padrao.py
  padrao/migrations/0002_remove_padrao_funcionario_remove_padrao_itens_and_more.py
  padrao/migrations/0003_alter_padraoequipamento_padrao_funcionario.py
  padrao/migrations/0003_initial.py
  padrao/migrations/0004_alter_padraoequipamento_padrao_funcionario.py
  padrao/migrations/0004_rename_cargo_padrao_nome.py
  padrao/migrations/0005_alter_padraoequipamento_padrao_funcionario.py
  padrao/migrations/0006_alter_padraoequipamento_padrao_funcionario.py
  padrao/models.py
  padrao/static/js/crud-padroes.js
  padrao/static/js/datatable-padroes.js
  padrao/static/js/edit-padroes/utils.js
  padrao/static/js/toggle-itens.js
  padrao/templates/modal/modal_padrao.html
  padrao/templates/padroes.html
  padrao/urls.py
  padrao/views.py
  sistema_epi_v2/settings/base.py
  solicitacao/static/js/clone.js
  solicitacao/templates/solicitacao.html
  static/css/crud.css
  static/js/clone.js
  usuario/admin.py
  usuario/migrations/0021_alter_usuario_funcionario.py
  usuario/migrations/0022_alter_usuario_funcionario.py
Labels: funcionalidade
